feat: Add clean command to dev.sh script
makinacorpus/DbToolsBundle pull request #184
Opened 2024-11-01 17:18 UTC by iNem0o

Hello

Add a new development helper command to completely clean up the Docker environment. This is useful for contributors who want to reset their development environment to a clean state.

The `clean` command performs the following:
- Stops and removes all containers
- Removes all Docker images used by the project
- Removes all associated volumes
- Cleans up any orphaned containers

Usage:
```sh
./dev.sh clean
```

Documentation has been adjusted accordingly to the change.

2024-11-04 10:07 UTC, SimonMellerin requested changes
Thanks a lot for this PR, it's nice to see people use this dev tool and improve it!

2024-11-04 10:07 UTC, SimonMellerin commented on dev.sh
> +    build|up|down|ps|checks|test_all|unittest|test|composer_update|notice|clean) do_$action "$@";;
May be you can add a little description above (like line 334 just after `unittest ...`

2024-11-04 14:06 UTC, SimonMellerin approved these changes
@pounard  may be you want to review this one

2024-11-05 08:16 UTC, pounard commented
It seems all good to me!

Pipeline is green, so let's merge this.

2024-11-05 08:17 UTC, merged

2024-11-05 08:17 UTC, pounard commented
@iNem0o thanks!

2024-11-05 08:17 UTC, pounard commented
It lack a line in the changelog, we'll have to add it.